sudo: false
dist: trusty

os:
 - linux
 - osx

language: d

d:
 - dmd-2.096.0
 - ldc-1.25.1
 - gdc
 - dmd-beta
 - ldc-beta
 - dmd
 - ldc

matrix:
  allow_failures:
   - os: osx
     d: gdc
   - d: dmd-beta
   - d: ldc-beta

addons:
  apt:
    packages:
      - libnetcdf-dev

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew install homebrew/science/netcdf;
   fi
